<template>
  <div class="space-y-6">
    <!-- Header Section -->
    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">ایجاد صفحه جدید</h1>
        <p class="text-gray-600 mt-1">صفحه جدید خود را ایجاد و منتشر کنید</p>
      </div>
      <div class="flex flex-col sm:flex-row gap-3">
        <button @click="goBack" class="btn-secondary">
          <i class="ti ti-arrow-right ml-2"></i>
          بازگشت
        </button>
        <button @click="saveDraft" class="btn-secondary" :disabled="isLoading">
          <i class="ti ti-device-floppy ml-2"></i>
          ذخیره پیش‌نویس
        </button>
        <button @click="publishPage" class="btn-primary" :disabled="isLoading">
          <i class="ti ti-send ml-2" v-if="!isLoading"></i>
          <i class="ti ti-loader animate-spin ml-2" v-else></i>
          {{ isLoading ? 'در حال انتشار...' : 'انتشار صفحه' }}
        </button>
      </div>
    </div>

    <!-- Form Section -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Main Content -->
      <div class="lg:col-span-2 space-y-6">
        <!-- Title -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <label class="block text-sm font-medium text-gray-700 mb-2">عنوان صفحه</label>
          <input
            v-model="form.title"
            type="text"
            placeholder="عنوان صفحه خود را وارد کنید..."
            class="input-field"
            :class="errors.title ? 'border-red-500 focus:ring-red-500' : ''"
          >
          <p v-if="errors.title" class="text-red-600 text-sm mt-1">{{ errors.title }}</p>
        </div>

        <!-- Excerpt -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <div class="flex items-center justify-between mb-2">
            <label class="block text-sm font-medium text-gray-700">خلاصه صفحه</label>
            <button
              @click="generateExcerptFromContent"
              type="button"
              class="text-xs px-2.5 py-1 bg-blue-50 text-blue-600 hover:bg-blue-100 rounded-md transition-colors flex items-center disabled:opacity-50 disabled:cursor-not-allowed"
              :disabled="!form.content"
              :title="!form.content ? 'ابتدا محتوا را وارد کنید' : 'تولید خودکار از محتوا'"
            >
              <i class="ti ti-sparkles ml-1"></i>
              تولید خودکار
            </button>
          </div>
          <textarea
            v-model="form.excerpt"
            rows="3"
            placeholder="خلاصه‌ای جذاب و مختصر از محتوای صفحه..."
            class="input-field resize-none"
            :class="errors.excerpt ? 'border-red-500 focus:ring-red-500' : ''"
          ></textarea>
          <p v-if="errors.excerpt" class="text-red-600 text-sm mt-1">{{ errors.excerpt }}</p>
          <div class="flex justify-between items-center mt-1">
            <p class="text-xs text-gray-500">{{ form.excerpt.length }}/200 کاراکتر</p>
            <p v-if="autoGeneratedExcerpt" class="text-xs text-green-600 flex items-center">
              <i class="ti ti-check ml-1"></i>
              تولید شد از محتوا
            </p>
          </div>
        </div>

        <!-- Content Editor -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <label class="block text-sm font-medium text-gray-700 mb-4">محتوای صفحه</label>
          
          <TinyMCEEditor
            v-model="form.content"
            placeholder="محتوای صفحه خود را اینجا بنویسید..."
            :height="400"
          />
          
          <p v-if="errors.content" class="text-red-600 text-sm mt-2">{{ errors.content }}</p>
          <div class="flex justify-between items-center mt-2">
            <p class="text-xs text-gray-500">{{ getContentLength() }} کاراکتر</p>
            <p v-if="!form.content" class="text-xs text-orange-500">
              <i class="ti ti-alert-circle ml-1"></i>
              محتوا خالی است - دکمه تولید خلاصه غیرفعال است
            </p>
          </div>
        </div>

        <!-- SEO Settings -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <i class="ti ti-seo ml-2"></i>
            تنظیمات SEO و متا
          </h3>
          
          <!-- Slug -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              اسلاگ (URL)
              <span class="text-xs text-gray-500 mr-1">(نامک)</span>
            </label>
            <div class="flex gap-2">
              <input
                v-model="form.slug"
                type="text"
                placeholder="url-friendly-slug"
                class="input-field flex-1 font-mono text-sm"
                @blur="validateSlug"
              >
              <button @click="generateSlug" type="button" class="btn-secondary whitespace-nowrap">
                <i class="ti ti-refresh ml-1"></i>
                تولید خودکار
              </button>
            </div>
            <p class="text-xs text-gray-500 mt-1 flex items-center">
              <i class="ti ti-link text-blue-500 ml-1"></i>
              پیش‌نمایش: /{{ form.slug || 'page-slug' }}
            </p>
          </div>

          <!-- Meta Title -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">عنوان متا (Meta Title)</label>
            <input
              v-model="form.metaTitle"
              type="text"
              placeholder="عنوان برای موتورهای جستجو..."
              class="input-field"
              maxlength="70"
            >
            <div class="flex justify-between text-xs mt-1">
              <span class="text-gray-500">{{ form.metaTitle.length }}/70 کاراکتر</span>
              <span v-if="form.metaTitle.length > 60" class="text-orange-500">بهینه: 50-60</span>
              <span v-else-if="form.metaTitle.length >= 50" class="text-green-500">✓ عالی</span>
            </div>
          </div>

          <!-- Meta Description -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">توضیحات متا (Meta Description)</label>
            <textarea
              v-model="form.metaDescription"
              rows="3"
              placeholder="توضیحات مختصر و جذاب برای موتورهای جستجو..."
              class="input-field resize-none"
              maxlength="170"
            ></textarea>
            <div class="flex justify-between text-xs mt-1">
              <span class="text-gray-500">{{ form.metaDescription.length }}/170 کاراکتر</span>
              <span v-if="form.metaDescription.length > 160" class="text-orange-500">بهینه: 150-160</span>
              <span v-else-if="form.metaDescription.length >= 150" class="text-green-500">✓ عالی</span>
            </div>
          </div>

          <!-- Open Graph Settings -->
          <div class="border-t pt-4 mt-4">
            <h4 class="text-sm font-medium text-gray-900 mb-3 flex items-center">
              <i class="ti ti-brand-facebook ml-1 text-blue-600"></i>
              Open Graph (شبکه‌های اجتماعی)
            </h4>
            
            <div class="mb-3">
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Title</label>
              <input
                v-model="form.ogTitle"
                type="text"
                placeholder="عنوان برای اشتراک‌گذاری (اختیاری)"
                class="input-field text-sm"
              >
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از عنوان متا</p>
            </div>
            
            <div class="mb-3">
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Description</label>
              <textarea
                v-model="form.ogDescription"
                rows="2"
                placeholder="توضیحات برای اشتراک‌گذاری (اختیاری)"
                class="input-field text-sm resize-none"
              ></textarea>
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از توضیحات متا</p>
            </div>
            
            <div>
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Image</label>
              <input
                v-model="form.ogImage"
                type="text"
                placeholder="لینک تصویر (اختیاری)"
                class="input-field text-sm"
              >
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از تصویر شاخص | توصیه: 1200×630px</p>
            </div>
          </div>

          <!-- SEO Preview -->
          <div class="border-t pt-4 mt-4">
            <h4 class="text-sm font-medium text-gray-900 mb-2">پیش‌نمایش در گوگل</h4>
            <div class="bg-gray-50 rounded-lg p-3 border">
              <div class="text-blue-600 text-sm hover:underline cursor-pointer">
                {{ form.metaTitle || form.title || 'عنوان صفحه شما' }}
              </div>
              <div class="text-green-700 text-xs mt-1">
                https://yoursite.com/{{ form.slug || 'page-slug' }}
              </div>
              <div class="text-gray-600 text-xs mt-1 line-clamp-2">
                {{ form.metaDescription || form.excerpt || 'توضیحات متا صفحه شما...' }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Sidebar -->
      <div class="space-y-6">
        <!-- Publish Settings -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">تنظیمات انتشار</h3>
          
          <!-- Status Dropdown -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">وضعیت</label>
            
            <div class="relative" v-click-outside="() => showStatusDropdown = false">
              <button
                @click="showStatusDropdown = !showStatusDropdown"
                type="button"
                class="input-field w-full text-right flex items-center justify-between"
              >
                <span class="flex items-center">
                  <i class="ti ml-2" :class="getStatusIcon(form.status)"></i>
                  {{ getStatusLabel(form.status) }}
                </span>
                <i class="ti ti-chevron-down text-gray-400"></i>
              </button>
              
              <ul
                v-if="showStatusDropdown"
                class="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg overflow-hidden p-0 m-0 list-none"
              >
                <li
                  v-for="status in statuses"
                  :key="status.value"
                  @click="selectStatus(status.value)"
                  class="px-3 py-2.5 hover:bg-gray-50 cursor-pointer text-sm flex items-center transition-colors"
                  :class="form.status === status.value ? 'bg-blue-50 text-blue-700' : ''"
                >
                  <i class="ti ml-2" :class="status.icon"></i>
                  <div class="flex-1">
                    <div class="font-medium">{{ status.label }}</div>
                    <div class="text-xs text-gray-500">{{ status.description }}</div>
                  </div>
                  <i v-if="form.status === status.value" class="ti ti-check text-blue-600"></i>
                </li>
              </ul>
            </div>
          </div>

          <!-- Template Dropdown -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">قالب صفحه</label>
            
            <div class="relative" v-click-outside="() => showTemplateDropdown = false">
              <button
                @click="showTemplateDropdown = !showTemplateDropdown"
                type="button"
                class="input-field w-full text-right flex items-center justify-between"
              >
                <span class="flex items-center">
                  <i class="ti ti-layout ml-2"></i>
                  {{ getTemplateLabel(form.template) }}
                </span>
                <i class="ti ti-chevron-down text-gray-400"></i>
              </button>
              
              <ul
                v-if="showTemplateDropdown"
                class="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg overflow-hidden p-0 m-0 list-none"
              >
                <li
                  v-for="template in templates"
                  :key="template.value"
                  @click="selectTemplate(template.value)"
                  class="px-3 py-2.5 hover:bg-gray-50 cursor-pointer text-sm flex items-center transition-colors"
                  :class="form.template === template.value ? 'bg-blue-50 text-blue-700' : ''"
                >
                  <i class="ti ti-layout ml-2"></i>
                  <div class="flex-1">
                    <div class="font-medium">{{ template.label }}</div>
                    <div class="text-xs text-gray-500">{{ template.description }}</div>
                  </div>
                  <i v-if="form.template === template.value" class="ti ti-check text-blue-600"></i>
                </li>
              </ul>
            </div>
          </div>

          <!-- Publish Date (Persian DatePicker) -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">تاریخ و زمان انتشار</label>
            
            <!-- Persian DatePicker Component -->
            <DatePicker
              v-model="form.publishDate"
              format="YYYY-MM-DD HH:mm:ss"
              display-format="jYYYY/jMM/jDD - ساعت HH:mm"
              type="datetime"
              :auto-submit="false"
              :clearable="true"
              placeholder="انتخاب تاریخ و زمان شمسی..."
              input-class="input-field cursor-pointer"
              :editable="false"
              locale="fa"
              :locale-config="{
                fa: {
                  lang: {
                    label: 'شمسی',
                    submit: 'تایید',
                    cancel: 'انصراف',
                    now: 'اکنون',
                    nextMonth: 'ماه بعد',
                    prevMonth: 'ماه قبل'
                  }
                }
              }"
            >
              <template #icon-calendar>
                <i class="ti ti-calendar-event text-gray-400"></i>
              </template>
            </DatePicker>
          </div>
        </div>

        <!-- Featured Image -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">تصویر شاخص</h3>
          
          <!-- Current Image -->
          <div v-if="form.image" class="mb-4">
            <img :src="form.image" alt="Featured Image" class="w-full h-32 object-cover rounded-lg">
            <button @click="removeImage" class="mt-2 text-sm text-red-600 hover:text-red-800">
              <i class="ti ti-trash ml-1"></i>
              حذف تصویر
            </button>
          </div>

          <!-- Upload Area -->
          <div
            @drop="handleDrop"
            @dragover.prevent="isDragging = true"
            @dragenter.prevent="isDragging = true"
            @dragleave.prevent="isDragging = false"
            class="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-orange-400 transition-colors cursor-pointer"
            :class="isDragging ? 'border-orange-400 bg-orange-50' : ''"
            @click="$refs.fileInput.click()"
          >
            <i class="ti ti-cloud-upload text-3xl text-gray-400 mb-2"></i>
            <p class="text-gray-600 mb-1">تصویر را اینجا بکشید یا کلیک کنید</p>
            <p class="text-sm text-gray-500">حداکثر 5MB - JPG, PNG, WebP</p>
            <input
              ref="fileInput"
              type="file"
              class="hidden"
              accept="image/*"
              @change="handleFileSelect"
            >
          </div>
        </div>

        <!-- Writing Tips -->
        <div class="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl border border-blue-200 p-6">
          <h3 class="text-lg font-medium text-blue-900 mb-3">
            <i class="ti ti-bulb ml-2"></i>
            نکات نوشتن
          </h3>
          <ul class="text-sm text-blue-800 space-y-2">
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>عنوان واضح و مرتبط انتخاب کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>خلاصه کوتاه و شفاف بنویسید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>محتوا را با عنوان‌های فرعی تقسیم کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>تصویر مناسب اضافه کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>قالب مناسب را انتخاب کنید</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Success/Error Notifications -->
  <div class="fixed bottom-20 lg:bottom-4 left-4 right-4 lg:right-auto z-50 space-y-2">
    <div
      v-for="notif in notifications"
      :key="notif.id"
      class="bg-white border rounded-lg shadow-lg p-4 min-w-[300px] animate-slide-up"
      :class="{
        'border-green-500': notif.type === 'success',
        'border-red-500': notif.type === 'error',
        'border-blue-500': notif.type === 'info'
      }"
    >
      <div class="flex items-center gap-3">
        <i class="ti text-xl" :class="{
          'ti-check-circle text-green-600': notif.type === 'success',
          'ti-alert-circle text-red-600': notif.type === 'error',
          'ti-info-circle text-blue-600': notif.type === 'info'
        }"></i>
        <p class="text-sm flex-1">{{ notif.message }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import TinyMCEEditor from '../../../components/TinyMCEEditor.vue'
import DatePicker from 'vue3-persian-datetime-picker'
import {useDanimPageStore} from "@/stores/danim-page.ts";

const router = useRouter()

const isLoading = ref(false)
const isDragging = ref(false)
const notifications = ref([])
const autoGeneratedExcerpt = ref(false)
const showStatusDropdown = ref(false)
const showTemplateDropdown = ref(false)

const form = reactive({
  title: '',
  slug: '',
  excerpt: '',
  content: '',
  status: 'draft',
  template: 'default',
  publishDate: null,
  image: null,
  metaTitle: '',
  metaDescription: '',
  ogTitle: '',
  ogDescription: '',
  ogImage: ''
})

const errors = reactive({
  title: '',
  excerpt: '',
  content: ''
})

const statuses = [
  { value: 'draft', label: 'پیش‌نویس', description: 'ذخیره بدون انتشار', icon: 'ti-file-text' },
  { value: 'published', label: 'منتشر شده', description: 'نمایش عمومی', icon: 'ti-check-circle' },
  { value: 'scheduled', label: 'زمان‌بندی شده', description: 'انتشار در تاریخ مشخص', icon: 'ti-clock' }
]

const templates = [
  { value: 'default', label: 'پیش‌فرض', description: 'قالب استاندارد با سایدبار' },
  { value: 'full-width', label: 'تمام عرض', description: 'بدون سایدبار، تمام پهنا' },
  { value: 'landing', label: 'لندینگ پیج', description: 'برای صفحات فرود' },
  { value: 'contact', label: 'تماس با ما', description: 'با فرم تماس' }
]

// Status Management
const getStatusLabel = (value) => {
  return statuses.find(s => s.value === value)?.label || 'پیش‌نویس'
}

const getStatusIcon = (value) => {
  return statuses.find(s => s.value === value)?.icon || 'ti-file-text'
}

const selectStatus = (value) => {
  form.status = value
  showStatusDropdown.value = false
}

// Template Management
const getTemplateLabel = (value) => {
  return templates.find(t => t.value === value)?.label || 'پیش‌فرض'
}

const selectTemplate = (value) => {
  form.template = value
  showTemplateDropdown.value = false
}

// Slug Management
const generateSlug = () => {
  if (form.title) {
    form.slug = form.title
      .toLowerCase()
      .trim()
      .replace(/[\s]+/g, '-')
      .replace(/[^\u0600-\u06FFa-z0-9\-]/g, '')
      .replace(/\-+/g, '-')
  }
}

const validateSlug = () => {
  form.slug = form.slug
    .toLowerCase()
    .trim()
    .replace(/[\s]+/g, '-')
    .replace(/[^\u0600-\u06FFa-z0-9\-]/g, '')
    .replace(/\-+/g, '-')
}

// Excerpt Management
const generateExcerptFromContent = () => {
  console.log('🔍 form.content:', form.content)
  
  if (!form.content || form.content.trim() === '') {
    showNotification('لطفا ابتدا محتوا را وارد کنید', 'error')
    return
  }
  
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = form.content
  const text = tempDiv.textContent || tempDiv.innerText || ''
  const cleanText = text.trim()
  
  if (!cleanText) {
    showNotification('محتوای قابل استخراج یافت نشد', 'error')
    return
  }
  
  form.excerpt = cleanText.substring(0, 200).trim()
  
  if (form.excerpt) {
    autoGeneratedExcerpt.value = true
    showNotification('خلاصه با موفقیت تولید شد', 'success')
    setTimeout(() => {
      autoGeneratedExcerpt.value = false
    }, 3000)
  }
}

// Content Length
const getContentLength = () => {
  if (!form.content) return 0
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = form.content
  const text = tempDiv.textContent || tempDiv.innerText || ''
  return text.length
}

// Image Management
const removeImage = () => {
  form.image = null
}

const handleDrop = (e) => {
  e.preventDefault()
  isDragging.value = false
  
  const files = e.dataTransfer?.files
  if (files && files.length > 0) {
    handleImageUpload(files[0])
  }
}

const handleFileSelect = (e) => {
  const files = e.target?.files
  if (files && files.length > 0) {
    handleImageUpload(files[0])
  }
}

const handleImageUpload = (file) => {
  if (file && file.type.startsWith('image/')) {
    const reader = new FileReader()
    reader.onload = (e) => {
      form.image = e.target?.result
      showNotification('تصویر با موفقیت آپلود شد', 'success')
    }
    reader.readAsDataURL(file)
  } else {
    showNotification('لطفا یک فایل تصویری انتخاب کنید', 'error')
  }
}

// Form Validation
const validateForm = () => {
  let isValid = true
  
  // Reset errors
  errors.title = ''
  errors.excerpt = ''
  errors.content = ''
  
  if (!form.title.trim()) {
    errors.title = 'عنوان صفحه الزامی است'
    isValid = false
  }
  
  if (!form.excerpt.trim()) {
    errors.excerpt = 'خلاصه صفحه الزامی است'
    isValid = false
  }
  
  if (!form.content.trim()) {
    errors.content = 'محتوای صفحه الزامی است'
    isValid = false
  }
  
  return isValid
}

// Save Functions
const saveDraft = () => {
  if (!form.title.trim()) {
    showNotification('لطفا عنوان صفحه را وارد کنید', 'error')
    return
  }
  
  form.status = 'draft'
  
  if (!form.slug) {
    generateSlug()
  }
  
  // Save to localStorage
  const pages = JSON.parse(localStorage.getItem('pages') || '[]')
  const newPage = {
    id: Date.now(),
    ...form,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    views: 0
  }
  pages.push(newPage)
  localStorage.setItem('pages', JSON.stringify(pages))
  
  showNotification('صفحه به عنوان پیش‌نویس ذخیره شد', 'success')
  
  setTimeout(() => {
    router.push('/dashboard/danim/pages')
  }, 1500)
}
const danimPageStore=useDanimPageStore()
const publishPage = async () => {
  if (!validateForm()) {
    showNotification('لطفا فیلدهای الزامی را پر کنید', 'error');
    return;
  }

  if (!form.slug) {
    generateSlug();
  }

  isLoading.value = true;

  try {
    // اضافه کردن صفحه از طریق store
    await danimPageStore.addPage({
      ...form,
      status: 'published',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      views: 0,
    });

    showNotification('صفحه با موفقیت منتشر شد! ✨', 'success');

    // هدایت بعد از انتشار
    setTimeout(() => {
      router.push('/dashboard/danim/pages');
    }, 1000);
  } catch (error) {
    console.error('❌ خطا در انتشار صفحه:', error);
    showNotification('خطا در انتشار صفحه!', 'error');
  } finally {
    isLoading.value = false;
  }
}

// Navigation
const goBack = () => {
  router.push('/dashboard/danim/pages')
}

// Notifications
const showNotification = (message, type = 'success') => {
  const id = Date.now()
  notifications.value.push({ id, message, type })
  
  setTimeout(() => {
    notifications.value = notifications.value.filter(n => n.id !== id)
  }, 3000)
}

// Click Outside Directive
const vClickOutside = {
  mounted(el, binding) {
    el.clickOutsideEvent = (event) => {
      if (!(el === event.target || el.contains(event.target))) {
        binding.value(event)
      }
    }
    document.addEventListener('click', el.clickOutsideEvent)
  },
  unmounted(el) {
    document.removeEventListener('click', el.clickOutsideEvent)
  }
}
</script>

<style scoped>
.input-field {
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid #e5e7eb;
  border-radius: 0.5rem;
  font-size: 0.875rem;
  transition: all 0.2s;
}

.input-field:focus {
  outline: none;
  border-color: #f97316;
  box-shadow: 0 0 0 3px rgba(249, 115, 22, 0.1);
}

.btn-primary {
  background-color: #f97316;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: all 0.2s;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.btn-primary:hover:not(:disabled) {
  background-color: #ea580c;
}

.btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-secondary {
  background-color: #f3f4f6;
  color: #374151;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: all 0.2s;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.btn-secondary:hover:not(:disabled) {
  background-color: #e5e7eb;
}

@keyframes slide-up {
  from {
    transform: translateY(1rem);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

.animate-slide-up {
  animation: slide-up 0.3s ease-out;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}

.animate-spin {
  animation: spin 1s linear infinite;
}

.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
