<template>
  <div class="space-y-6">
    <!-- Header Section -->
    <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">ایجاد نوشته جدید</h1>
        <p class="text-gray-600 mt-1">نوشته جدید خود را ایجاد و منتشر کنید</p>
      </div>
      <div class="flex flex-col sm:flex-row gap-3">
        <button @click="goBack" class="btn-secondary">
          <i class="ti ti-arrow-right ml-2"></i>
          بازگشت
        </button>
        <button @click="saveDraft" class="btn-secondary" :disabled="isLoading">
          <i class="ti ti-device-floppy ml-2"></i>
          ذخیره پیش‌نویس
        </button>
        <button @click="publishPost" class="btn-primary" :disabled="isLoading">
          <i class="ti ti-send ml-2" v-if="!isLoading"></i>
          <i class="ti ti-loader animate-spin ml-2" v-else></i>
          {{ isLoading ? 'در حال انتشار...' : 'انتشار نوشته' }}
        </button>
      </div>
    </div>

    <!-- Form Section -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Main Content -->
      <div class="lg:col-span-2 space-y-6">
        <!-- Title -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <label class="block text-sm font-medium text-gray-700 mb-2">عنوان نوشته</label>
          <input
              v-model="form.title"
              type="text"
              placeholder="عنوان جذاب برای نوشته خود وارد کنید..."
              class="input-field"
              :class="errors.title ? 'border-red-500 focus:ring-red-500' : ''"
          >
          <p v-if="errors.title" class="text-red-600 text-sm mt-1">{{ errors.title }}</p>
        </div>

        <!-- Excerpt with Auto-generate -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <div class="flex items-center justify-between mb-2">
            <label class="block text-sm font-medium text-gray-700">خلاصه نوشته</label>
            <button
                @click="generateExcerptFromContent"
                type="button"
                class="text-xs px-2.5 py-1 bg-blue-50 text-blue-600 hover:bg-blue-100 rounded-md transition-colors flex items-center"
                :disabled="!form.content"
            >
              <i class="ti ti-sparkles ml-1"></i>
              تولید خودکار
            </button>
          </div>
          <textarea
              v-model="form.excerpt"
              rows="3"
              placeholder="خلاصه‌ای جذاب و مختصر از محتوای نوشته..."
              class="input-field resize-none"
              :class="errors.excerpt ? 'border-red-500 focus:ring-red-500' : ''"
          ></textarea>
          <p v-if="errors.excerpt" class="text-red-600 text-sm mt-1">{{ errors.excerpt }}</p>
          <div class="flex justify-between items-center mt-1">
            <p class="text-xs text-gray-500">{{ form.excerpt.length }}/200 کاراکتر</p>
            <p v-if="autoGeneratedExcerpt" class="text-xs text-green-600 flex items-center">
              <i class="ti ti-check ml-1"></i>
              تولید شد از محتوا
            </p>
          </div>
        </div>

        <!-- Content Editor -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <label class="block text-sm font-medium text-gray-700 mb-4">محتوای نوشته</label>

          <TinyMCEEditor
              v-model="form.content"
              placeholder="محتوای نوشته خود را اینجا بنویسید..."
              :height="400"
          />

          <p v-if="errors.content" class="text-red-600 text-sm mt-2">{{ errors.content }}</p>
          <p class="text-xs text-gray-500 mt-2">{{ getContentLength() }} کاراکتر</p>
        </div>

        <!-- SEO Settings -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <i class="ti ti-seo ml-2"></i>
            تنظیمات SEO و متا
          </h3>

          <!-- Slug -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              اسلاگ (URL)
              <span class="text-xs text-gray-500 mr-1">(نامک)</span>
            </label>
            <div class="flex gap-2">
              <input
                  v-model="form.slug"
                  type="text"
                  placeholder="url-friendly-slug"
                  class="input-field flex-1 font-mono text-sm"
                  @blur="validateSlug"
              >
              <button @click="generateSlug" type="button" class="btn-secondary whitespace-nowrap">
                <i class="ti ti-refresh ml-1"></i>
                تولید خودکار
              </button>
            </div>
            <p class="text-xs text-gray-500 mt-1 flex items-center">
              <i class="ti ti-link text-blue-500 ml-1"></i>
              پیش‌نمایش: /blog/{{ form.slug || 'post-slug' }}
            </p>
          </div>

          <!-- Meta Title -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">عنوان متا (Meta Title)</label>
            <input
                v-model="form.metaTitle"
                type="text"
                placeholder="عنوان برای موتورهای جستجو..."
                class="input-field"
                maxlength="70"
            >
            <div class="flex justify-between text-xs mt-1">
              <span class="text-gray-500">{{ form.metaTitle.length }}/70 کاراکتر</span>
              <span v-if="form.metaTitle.length > 60" class="text-orange-500">بهینه: 50-60</span>
              <span v-else-if="form.metaTitle.length >= 50" class="text-green-500">✓ عالی</span>
            </div>
          </div>

          <!-- Meta Description -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">توضیحات متا (Meta Description)</label>
            <textarea
                v-model="form.metaDescription"
                rows="3"
                placeholder="توضیحات مختصر و جذاب برای موتورهای جستجو..."
                class="input-field resize-none"
                maxlength="170"
            ></textarea>
            <div class="flex justify-between text-xs mt-1">
              <span class="text-gray-500">{{ form.metaDescription.length }}/170 کاراکتر</span>
              <span v-if="form.metaDescription.length > 160" class="text-orange-500">بهینه: 150-160</span>
              <span v-else-if="form.metaDescription.length >= 150" class="text-green-500">✓ عالی</span>
            </div>
          </div>

          <!-- Open Graph Settings -->
          <div class="border-t pt-4 mt-4">
            <h4 class="text-sm font-medium text-gray-900 mb-3 flex items-center">
              <i class="ti ti-brand-facebook ml-1 text-blue-600"></i>
              Open Graph (شبکه‌های اجتماعی)
            </h4>

            <div class="mb-3">
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Title</label>
              <input
                  v-model="form.ogTitle"
                  type="text"
                  placeholder="عنوان برای اشتراک‌گذاری (اختیاری)"
                  class="input-field text-sm"
              >
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از عنوان متا</p>
            </div>

            <div class="mb-3">
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Description</label>
              <textarea
                  v-model="form.ogDescription"
                  rows="2"
                  placeholder="توضیحات برای اشتراک‌گذاری (اختیاری)"
                  class="input-field text-sm resize-none"
              ></textarea>
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از توضیحات متا</p>
            </div>

            <div>
              <label class="block text-xs font-medium text-gray-700 mb-1">OG Image</label>
              <input
                  v-model="form.ogImage"
                  type="text"
                  placeholder="لینک تصویر (اختیاری)"
                  class="input-field text-sm"
              >
              <p class="text-xs text-gray-500 mt-1">خالی = استفاده از تصویر شاخص | توصیه: 1200×630px</p>
            </div>
          </div>

          <!-- Schema.org Settings -->
          <div class="border-t pt-4 mt-4">
            <h4 class="text-sm font-medium text-gray-900 mb-3 flex items-center">
              <i class="ti ti-code ml-1 text-purple-600"></i>
              Schema.org (داده ساختاریافته)
            </h4>

            <div class="mb-3">
              <label class="block text-xs font-medium text-gray-700 mb-1">نوع محتوا</label>

              <div class="relative" v-click-outside="() => showSchemaDropdown = false">
                <button
                    @click="showSchemaDropdown = !showSchemaDropdown"
                    type="button"
                    class="input-field text-sm w-full text-right flex items-center justify-between"
                >
                  <span class="flex items-center">
                    <i class="ti ti-file-type-html ml-1 text-purple-600"></i>
                    {{ getSchemaLabel(form.schemaType) }}
                  </span>
                  <i class="ti ti-chevron-down text-gray-400"></i>
                </button>

                <ul
                    v-if="showSchemaDropdown"
                    class="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg overflow-hidden p-0 m-0 list-none"
                >
                  <li
                      v-for="schema in schemaTypes"
                      :key="schema.value"
                      @click="selectSchemaType(schema.value)"
                      class="px-3 py-2 hover:bg-gray-50 cursor-pointer text-xs transition-colors"
                      :class="form.schemaType === schema.value ? 'bg-purple-50 text-purple-700' : ''"
                  >
                    <div class="font-medium">{{ schema.label }}</div>
                    <div class="text-gray-500 mt-0.5">{{ schema.description }}</div>
                  </li>
                </ul>
              </div>
            </div>

            <div>
              <label class="block text-xs font-medium text-gray-700 mb-1">کلمات کلیدی</label>
              <input
                  v-model="form.keywords"
                  type="text"
                  placeholder="کلمات کلیدی، با ویرگول جدا شود"
                  class="input-field text-sm"
              >
              <p class="text-xs text-gray-500 mt-1">مثال: سگ، گربه، حیوانات خانگی</p>
            </div>
          </div>

          <!-- SEO Preview -->
          <div class="border-t pt-4 mt-4">
            <h4 class="text-sm font-medium text-gray-900 mb-2">پیش‌نمایش در گوگل</h4>
            <div class="bg-gray-50 rounded-lg p-3 border">
              <div class="text-blue-600 text-sm hover:underline cursor-pointer">
                {{ form.metaTitle || form.title || 'عنوان نوشته شما' }}
              </div>
              <div class="text-green-700 text-xs mt-1">
                https://yoursite.com/blog/{{ form.slug || 'post-slug' }}
              </div>
              <div class="text-gray-600 text-xs mt-1 line-clamp-2">
                {{ form.metaDescription || form.excerpt || 'توضیحات متا نوشته شما...' }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Sidebar -->
      <div class="space-y-6">
        <!-- Publish Settings -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">تنظیمات انتشار</h3>

          <!-- Status Dropdown -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">وضعیت</label>

            <div class="relative" v-click-outside="() => showStatusDropdown = false">
              <button
                  @click="showStatusDropdown = !showStatusDropdown"
                  type="button"
                  class="input-field w-full text-right flex items-center justify-between"
              >
                <span class="flex items-center">
                  <i class="ti ml-2" :class="getStatusIcon(form.status)"></i>
                  {{ getStatusLabel(form.status) }}
                </span>
                <i class="ti ti-chevron-down text-gray-400"></i>
              </button>

              <ul
                  v-if="showStatusDropdown"
                  class="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg overflow-hidden p-0 m-0 list-none"
              >
                <li
                    v-for="status in statuses"
                    :key="status.value"
                    @click="selectStatus(status.value)"
                    class="px-3 py-2.5 hover:bg-gray-50 cursor-pointer text-sm flex items-center transition-colors"
                    :class="form.status === status.value ? 'bg-blue-50 text-blue-700' : ''"
                >
                  <i class="ti ml-2" :class="status.icon"></i>
                  <div class="flex-1">
                    <div class="font-medium">{{ status.label }}</div>
                    <div class="text-xs text-gray-500">{{ status.description }}</div>
                  </div>
                  <i v-if="form.status === status.value" class="ti ti-check text-blue-600"></i>
                </li>
              </ul>
            </div>
          </div>

          <!-- Publish Date (Persian DatePicker) -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">تاریخ و زمان انتشار</label>

            <!-- Persian DatePicker Component -->
            <DatePicker
                v-model="form.publishDate"
                format="YYYY-MM-DD HH:mm:ss"
                display-format="jYYYY/jMM/jDD - ساعت HH:mm"
                type="datetime"
                :auto-submit="false"
                :clearable="true"
                placeholder="انتخاب تاریخ و زمان شمسی..."
                input-class="input-field cursor-pointer"
                :editable="false"
                locale="fa"
                :locale-config="{
                fa: {
                  lang: {
                    label: 'شمسی',
                    submit: 'تایید',
                    cancel: 'انصراف',
                    now: 'اکنون',
                    nextMonth: 'ماه بعد',
                    prevMonth: 'ماه قبل'
                  }
                }
              }"
            >
              <template #icon-calendar>
                <i class="ti ti-calendar-event text-gray-400"></i>
              </template>
            </DatePicker>
          </div>
        </div>

        <!-- Category Block (Separate) -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">دسته‌بندی‌ها</h3>

          <!-- Selected Categories Display -->
          <div v-if="form.categories.length > 0" class="mb-3 flex flex-wrap gap-2">
            <span
                v-for="(catId, index) in form.categories"
                :key="catId"
                class="inline-flex items-center px-3 py-1.5 rounded-lg text-sm font-medium bg-blue-100 text-blue-800 border border-blue-200"
            >
              <i class="ti ti-folder ml-1.5"></i>
              {{ getCategoryPath(catId) }}
              <button @click="removeCategory(index)" class="mr-2 hover:text-blue-600">
                <i class="ti ti-x text-sm"></i>
              </button>
            </span>
          </div>

          <!-- Category Dropdown with Search -->
          <div class="relative" v-click-outside="() => showCategoryDropdown = false">
            <div class="relative">
              <input
                  v-model="categorySearch"
                  @focus="showCategoryDropdown = true"
                  @input="filterCategories"
                  type="text"
                  placeholder="جستجو یا انتخاب دسته‌بندی..."
                  class="input-field pr-10"
                  :class="errors.category ? 'border-red-500' : ''"
              >
              <i class="ti ti-search absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></i>
            </div>

            <!-- Dropdown Tree List -->
            <div
                v-if="showCategoryDropdown"
                class="absolute z-20 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-96 overflow-y-auto"
            >
              <!-- Add New Category Section -->
              <div class="sticky top-0 bg-gray-50 border-b border-gray-200 p-2">
                <button
                    @click="showAddCategoryModal = true; showCategoryDropdown = false"
                    type="button"
                    class="w-full px-3 py-2 bg-green-50 hover:bg-green-100 text-green-700 rounded-md text-sm font-medium flex items-center justify-center transition-colors"
                >
                  <i class="ti ti-plus ml-2"></i>
                  افزودن دسته جدید
                </button>
              </div>

              <!-- Category Tree as UL/LI -->
              <ul class="p-0 m-0 list-none">
                <li v-if="filteredCategoryTree.length === 0" class="px-3 py-8 text-center text-gray-500 text-sm">
                  <i class="ti ti-folder-off text-3xl mb-2 block"></i>
                  نتیجه‌ای یافت نشد
                </li>

                <CategoryTreeItem
                    v-for="category in filteredCategoryTree"
                    :key="category.id"
                    :category="category"
                    :selected-ids="form.categories"
                    :level="0"
                    @toggle="toggleCategory"
                    @select="selectCategoryItem"
                />
              </ul>
            </div>
          </div>

          <p v-if="errors.category" class="text-red-600 text-sm mt-1">{{ errors.category }}</p>
          <p class="text-xs text-gray-500 mt-1 flex items-center">
            <i class="ti ti-info-circle ml-1"></i>
            می‌توانید چندین دسته انتخاب کنید
          </p>
        </div>

        <!-- Tags Block (Separate) -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">برچسب‌ها</h3>
          <!-- پیشنهادات -->
          <div class="flex flex-wrap gap-2 mb-2">
  <span
      v-for="tag in tagStore.tags"
      :key="tag.name"
      @click="addTag(tag.name)"
      class="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm cursor-pointer hover:bg-rose-100 hover:text-rose-700"
  >
    {{ tag.name }} ({{ tag.count }})
  </span>
          </div>
          <!-- تگ‌های انتخاب‌شده -->
          <div class="flex flex-wrap gap-2 mb-2">
         <span v-for="(tag, index) in form.tags" :key="index"
               class="px-3 py-1 bg-rose-100 text-rose-700 rounded-full text-sm flex items-center gap-2">
    {{ tag }}
    <button type="button" @click="removeTag(index)" class="hover:text-rose-900">
      <i class="ti ti-x text-xs"></i>
    </button>
  </span>
          </div>
          <!-- ورودی تگ جدید -->
          <div class="flex gap-2">
            <input
                v-model="newTag"
                type="text"
                @keypress.enter.prevent="addTag()"
                class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-rose-500 focus:border-transparent"
                placeholder="برچسب جدید را وارد کنید..."
            >
            <button type="button" @click="addTag()"
                    class="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200">
              <i class="ti ti-plus"></i>
            </button>
          </div>

        </div>

        <!-- Featured Image -->
        <div class="bg-white rounded-xl border border-gray-200 p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">تصویر شاخص</h3>

          <!-- Current Image -->
          <div v-if="form.image" class="mb-4">
            <img :src="form.image" alt="Featured Image" class="w-full h-32 object-cover rounded-lg">
            <button @click="removeImage" class="mt-2 text-sm text-red-600 hover:text-red-800">
              <i class="ti ti-trash ml-1"></i>
              حذف تصویر
            </button>
          </div>

          <!-- Upload Area -->
          <div
              @drop="handleDrop"
              @dragover.prevent="isDragging = true"
              @dragenter.prevent="isDragging = true"
              @dragleave.prevent="isDragging = false"
              class="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-orange-400 transition-colors cursor-pointer"
              :class="isDragging ? 'border-orange-400 bg-orange-50' : ''"
              @click="$refs.fileInput.click()"
          >
            <i class="ti ti-cloud-upload text-3xl text-gray-400 mb-2"></i>
            <p class="text-gray-600 mb-1">تصویر را اینجا بکشید یا کلیک کنید</p>
            <p class="text-sm text-gray-500">حداکثر 5MB - JPG, PNG, WebP</p>
            <input
                ref="fileInput"
                type="file"
                class="hidden"
                accept="image/*"
                @change="handleFileSelect"
            >
          </div>
        </div>

        <!-- Writing Tips -->
        <div class="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl border border-blue-200 p-6">
          <h3 class="text-lg font-medium text-blue-900 mb-3">
            <i class="ti ti-bulb ml-2"></i>
            نکات نوشتن
          </h3>
          <ul class="text-sm text-blue-800 space-y-2">
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>عنوان جذاب و مرتبط انتخاب کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>خلاصه کوتاه و شفاف بنویسید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>محتوا را با عنوان‌های فرعی تقسیم کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>تصویر مناسب اضافه کنید</span>
            </li>
            <li class="flex items-start gap-2">
              <i class="ti ti-check text-blue-600 mt-0.5 flex-shrink-0"></i>
              <span>برچسب‌های مرتبط انتخاب کنید</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Category Modal -->
  <div
      v-if="showAddCategoryModal"
      class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
      @click.self="showAddCategoryModal = false"
  >
    <div class="bg-white rounded-xl shadow-2xl max-w-md w-full p-6 animate-modal">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-xl font-bold text-gray-900 flex items-center">
          <i class="ti ti-folder-plus ml-2 text-green-600"></i>
          افزودن دسته‌بندی جدید
        </h3>
        <button @click="showAddCategoryModal = false" class="text-gray-400 hover:text-gray-600">
          <i class="ti ti-x text-xl"></i>
        </button>
      </div>

      <div class="space-y-4">
        <!-- Category Name -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">نام دسته‌بندی *</label>
          <input
              v-model="newCategoryForm.title"
              type="text"
              placeholder="مثال: سلامت حیوانات"
              class="input-field"
              @keyup.enter="saveNewCategory"
          >
        </div>

        <!-- Parent Category -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">دسته والد (اختیاری)</label>
          <div class="relative" v-click-outside="() => showParentDropdown = false">
            <button
                @click="showParentDropdown = !showParentDropdown"
                type="button"
                class="input-field w-full text-right flex items-center justify-between"
            >
              <span class="flex items-center text-gray-700">
                <i class="ti ml-2"
                   :class="newCategoryForm.parentId ? 'ti-folder text-blue-600' : 'ti-folder-off text-gray-400'"></i>
                {{ newCategoryForm.parentId ? getCategoryName(newCategoryForm.parentId) : 'دسته اصلی (بدون والد)' }}
              </span>
              <i class="ti ti-chevron-down text-gray-400"></i>
            </button>

            <div
                v-if="showParentDropdown"
                class="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-60 overflow-y-auto"
            >
              <ul class="p-0 m-0 list-none">
                <!-- No Parent Option -->
                <li
                    @click="newCategoryForm.parentId = null; showParentDropdown = false"
                    class="px-3 py-2 hover:bg-gray-50 cursor-pointer text-sm flex items-center transition-colors"
                    :class="!newCategoryForm.parentId ? 'bg-blue-50 text-blue-700' : ''"
                >
                  <i class="ti ti-folder-off ml-2 text-gray-400"></i>
                  دسته اصلی (بدون والد)
                </li>

                <!-- Parent Categories Tree -->
                <ParentCategoryItem
                    v-for="category in categories"
                    :key="category.id"
                    :category="category"
                    :selected-id="newCategoryForm.parentId"
                    :level="0"
                    @select="selectParentCategory"
                />
              </ul>
            </div>
          </div>
          <p class="text-xs text-gray-500 mt-1">اگر دسته والد انتخاب کنید، این دسته زیرمجموعه آن خواهد بود</p>
        </div>

        <!-- Category Slug -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">نامک (Slug)</label>
          <input
              v-model="newCategoryForm.slug"
              type="text"
              placeholder="health-animals"
              class="input-field font-mono text-sm"
          >
          <p class="text-xs text-gray-500 mt-1">خالی = تولید خودکار از نام</p>
        </div>

        <!-- Description -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">توضیحات (اختیاری)</label>
          <textarea
              v-model="newCategoryForm.description"
              rows="3"
              placeholder="توضیحات مختصر درباره این دسته..."
              class="input-field resize-none text-sm"
          ></textarea>
        </div>
      </div>

      <div class="flex gap-3 mt-6">
        <button
            @click="showAddCategoryModal = false"
            type="button"
            class="flex-1 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
        >
          انصراف
        </button>
        <button
            @click="saveNewCategory"
            type="button"
            class="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium"
            :disabled="!newCategoryForm.title.trim()"
        >
          <i class="ti ti-check ml-2"></i>
          ذخیره دسته
        </button>
      </div>
    </div>
  </div>

  <!-- Notifications -->
  <div class="fixed bottom-4 left-4 z-50 space-y-2">
    <div
        v-for="notification in notifications"
        :key="notification.id"
        class="bg-white border border-gray-200 rounded-lg shadow-lg p-4 min-w-[300px] transform transition-all duration-300"
        :class="{
        'border-green-200 bg-green-50': notification.type === 'success',
        'border-red-200 bg-red-50': notification.type === 'error',
        'border-orange-200 bg-orange-50': notification.type === 'warning',
        'border-blue-200 bg-blue-50': notification.type === 'info'
      }"
    >
      <div class="flex items-start gap-3">
        <div class="flex-shrink-0">
          <i
              class="text-lg"
              :class="{
              'ti ti-check text-green-600': notification.type === 'success',
              'ti ti-x text-red-600': notification.type === 'error',
              'ti ti-alert-triangle text-orange-600': notification.type === 'warning',
              'ti ti-info-circle text-blue-600': notification.type === 'info'
            }"
          ></i>
        </div>
        <div class="flex-1">
          <p class="text-sm font-medium" :class="{
            'text-green-800': notification.type === 'success',
            'text-red-800': notification.type === 'error',
            'text-orange-800': notification.type === 'warning',
            'text-blue-800': notification.type === 'info'
          }">
            {{ notification.message }}
          </p>
          <div class="mt-2 bg-gray-200 rounded-full h-1">
            <div
                class="h-1 rounded-full transition-all duration-75"
                :class="{
                'bg-green-500': notification.type === 'success',
                'bg-red-500': notification.type === 'error',
                'bg-orange-500': notification.type === 'warning',
                'bg-blue-500': notification.type === 'info'
              }"
                :style="{ width: notification.progress + '%' }"
            ></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import {ref, reactive, computed, onMounted, watch} from 'vue'
import TinyMCEEditor from '../../../components/TinyMCEEditor.vue'
import CategoryTreeItem from '../../../components/CategoryTreeItem.vue'
import ParentCategoryItem from '../../../components/ParentCategoryItem.vue'
import DatePicker from 'vue3-persian-datetime-picker'
import {usePostStore} from "@/stores/post.ts";
import {useCategoryStore} from "@/stores/category.ts";
import {useCategoryTypeStore} from "@/stores/category-type.ts";
import {useTagStore} from "@/stores/tag.ts";
import {useTagTypeStore} from "@/stores/tag-type.ts";

const isLoading = ref(false)
const showPreviewModal = ref(false)
const isDragging = ref(false)
const newTag = ref('')
const tagTypeStore = useTagTypeStore()
const tagStore=useTagStore()
const notifications = ref([])
const autoGeneratedExcerpt = ref(false)
const categoryTypeStore = useCategoryTypeStore()
const categoryStore = useCategoryStore()
// Category Management - Tree Structure
const categoryTree = computed(() => categoryStore.categoryTree)
const categories = computed(() => categoryStore.categories)
/*const categoryTree = ref([
  {
    id: 1,
    name: 'سلامت حیوانات',
    slug: 'health',
    parentId: null,
    children: [
      { id: 2, name: 'واکسیناسیون', slug: 'vaccination', parentId: 1, children: [] },
      { id: 3, name: 'بیماری‌های رایج', slug: 'common-diseases', parentId: 1, children: [] }
    ]
  },
  {
    id: 4,
    name: 'تغذیه',
    slug: 'nutrition',
    parentId: null,
    children: [
      { id: 5, name: 'غذای خشک', slug: 'dry-food', parentId: 4, children: [] },
      { id: 6, name: 'غذای تر', slug: 'wet-food', parentId: 4, children: [] }
    ]
  },
  {
    id: 7,
    name: 'رفتار',
    slug: 'behavior',
    parentId: null,
    children: []
  }
])*/

const categorySearch = ref('')
const showCategoryDropdown = ref(false)
const filteredCategoryTree = ref([...categoryTree.value])
const showAddCategoryModal = ref(false)
const showParentDropdown = ref(false)

const newCategoryForm = reactive({
  typId: null,
  title: '',
  slug: '',
  parentId: null,
  description: ''
})

// Status Management
const statuses = [
  {
    value: 'draft',
    label: 'پیش‌نویس',
    icon: 'ti-file-pencil text-gray-500',
    description: 'قابل مشاهده فقط برای شما'
  },
  {
    value: 'published',
    label: 'منتشر شده',
    icon: 'ti-check text-green-600',
    description: 'عمومی و قابل دسترس برای همه'
  },
  {
    value: 'pending',
    label: 'در انتظار تایید',
    icon: 'ti-clock text-orange-500',
    description: 'نیاز به بررسی مدیر'
  }
]
const showStatusDropdown = ref(false)

// Schema Type Management
const schemaTypes = [
  {
    value: 'Article',
    label: 'مقاله (Article)',
    description: 'محتوای عمومی و مقالات استاندارد'
  },
  {
    value: 'BlogPosting',
    label: 'پست وبلاگ (BlogPosting)',
    description: 'پست‌های وبلاگ و مطالب شخصی'
  },
  {
    value: 'NewsArticle',
    label: 'خبر (NewsArticle)',
    description: 'اخبار و گزارش‌های خبری'
  },
  {
    value: 'TechArticle',
    label: 'مقاله تخصصی (TechArticle)',
    description: 'مقالات فنی و تخصصی'
  }
]
const showSchemaDropdown = ref(false)

// Form data
const form = reactive({
  title: '',
  slug: '',
  excerpt: '',
  content: '',
  categories: [], // Changed from category to categories (array)
  status: 'draft',
  tags: [],
  image: '',
  metaTitle: '',
  metaDescription: '',
  ogTitle: '',
  ogDescription: '',
  ogImage: '',
  schemaType: 'BlogPosting',
  keywords: '',
  publishDate: ''
})

// Validation errors
const errors = reactive({
  title: '',
  excerpt: '',
  content: '',
  category: ''
})

// Auto-generate Excerpt from Content
const generateExcerptFromContent = () => {
  if (!form.content) {
    showNotification('ابتدا محتوا را بنویسید', 'warning')
    return
  }

  // Remove HTML tags
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = form.content
  let textContent = tempDiv.textContent || tempDiv.innerText || ''

  // Clean up extra spaces and line breaks
  textContent = textContent.replace(/\s+/g, ' ').trim()

  // Get first 150-200 characters
  const maxLength = 200
  let excerpt = textContent.substring(0, maxLength)

  // Try to end at a sentence or word boundary
  if (textContent.length > maxLength) {
    // Try to find last period
    const lastPeriod = excerpt.lastIndexOf('.')
    const lastQuestion = excerpt.lastIndexOf('؟')
    const lastExclamation = excerpt.lastIndexOf('!')

    const lastSentence = Math.max(lastPeriod, lastQuestion, lastExclamation)

    if (lastSentence > maxLength * 0.6) {
      excerpt = excerpt.substring(0, lastSentence + 1)
    } else {
      // Find last space
      const lastSpace = excerpt.lastIndexOf(' ')
      if (lastSpace > maxLength * 0.7) {
        excerpt = excerpt.substring(0, lastSpace) + '...'
      } else {
        excerpt = excerpt + '...'
      }
    }
  }

  form.excerpt = excerpt
  autoGeneratedExcerpt.value = true
  showNotification('خلاصه با موفقیت از محتوا تولید شد', 'success')

  // Reset flag after 3 seconds
  setTimeout(() => {
    autoGeneratedExcerpt.value = false
  }, 3000)
}

// Auto-generate slug from title
watch(() => form.title, (newTitle) => {
  if (!form.slug || form.slug === '') {
    form.slug = generateSlugFromText(newTitle)
  }
  // Auto-fill meta title if empty
  if (!form.metaTitle) {
    form.metaTitle = newTitle
  }
})

watch(() => form.excerpt, (newExcerpt) => {
  // Auto-fill meta description if empty
  if (!form.metaDescription) {
    form.metaDescription = newExcerpt
  }
})

// Slug Generation
const generateSlugFromText = (text) => {
  if (!text) return ''

  // Persian to English mapping
  const persianToEnglish = {
    'آ': 'a', 'ا': 'a', 'ب': 'b', 'پ': 'p', 'ت': 't', 'ث': 's', 'ج': 'j', 'چ': 'ch',
    'ح': 'h', 'خ': 'kh', 'د': 'd', 'ذ': 'z', 'ر': 'r', 'ز': 'z', 'ژ': 'zh', 'س': 's',
    'ش': 'sh', 'ص': 's', 'ض': 'z', 'ط': 't', 'ظ': 'z', 'ع': 'a', 'غ': 'gh', 'ف': 'f',
    'ق': 'gh', 'ک': 'k', 'گ': 'g', 'ل': 'l', 'م': 'm', 'ن': 'n', 'و': 'v', 'ه': 'h',
    'ی': 'i', 'ئ': 'i', 'ة': 'e', 'ى': 'i', 'ي': 'i'
  }

  let slug = text.toLowerCase().trim()

  // Convert Persian to English
  slug = slug.split('').map(char => persianToEnglish[char] || char).join('')

  // Replace spaces and special chars with dash
  slug = slug.replace(/[\s_]+/g, '-')
  slug = slug.replace(/[^\w\-]+/g, '')
  slug = slug.replace(/\-\-+/g, '-')
  slug = slug.replace(/^-+/, '')
  slug = slug.replace(/-+$/, '')

  return slug
}

const generateSlug = () => {
  form.slug = generateSlugFromText(form.title)
  showNotification('اسلاگ تولید شد', 'success')
}

const validateSlug = () => {
  form.slug = form.slug.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/--+/g, '-')
}

// Status Management
const getStatusLabel = (value) => {
  const status = statuses.find(s => s.value === value)
  return status ? status.label : 'انتخاب وضعیت'
}

const getStatusIcon = (value) => {
  const status = statuses.find(s => s.value === value)
  return status ? status.icon : 'ti-help-circle text-gray-400'
}

const selectStatus = (value) => {
  form.status = value
  showStatusDropdown.value = false
}

// Schema Type Management
const getSchemaLabel = (value) => {
  const schema = schemaTypes.find(s => s.value === value)
  return schema ? schema.label : 'انتخاب نوع'
}

const selectSchemaType = (value) => {
  form.schemaType = value
  showSchemaDropdown.value = false
}

// Category Management - Tree Functions
const flattenCategoryTree = (tree, result = []) => {
  tree.forEach(cat => {
    result.push(cat)
    if (cat.children && cat.children.length > 0) {
      flattenCategoryTree(cat.children, result)
    }
  })
  return result
}

const findCategoryById = (id, tree = categoryTree.value) => {

  for (const cat of tree) {

    if (cat.id === id) return cat
    if (cat.children && cat.children.length > 0) {
      const found = findCategoryById(id, cat.children)
      if (found) return found
    }
  }
  return null
}

const getCategoryName = (id) => {
  const cat = findCategoryById(id)
  return cat ? cat.title : ''
}

const getCategoryPath = (id) => {
  const cat = findCategoryById(id)

  if (!cat) return ''

  let path = cat.title
  let parent = findCategoryById(cat.parentId)

  while (parent) {
    path = parent.title + ' > ' + path
    parent = findCategoryById(parent.parentId)
  }

  return path
}

const filterCategories = () => {
  if (!categorySearch.value) {
    filteredCategoryTree.value = [...categoryTree.value]
  } else {
    const search = categorySearch.value.toLowerCase()
    const allCategories = flattenCategoryTree(categoryTree.value)
    const matched = allCategories.filter(cat =>
        cat.title.toLowerCase().includes(search)
    )

    // Build tree structure from matched categories
    const matchedIds = new Set(matched.map(c => c.id))
    const buildFilteredTree = (tree) => {
      return tree.map(cat => {
        const newCat = {...cat}
        if (cat.children && cat.children.length > 0) {
          newCat.children = buildFilteredTree(cat.children)
        }
        return newCat
      }).filter(cat =>
          matchedIds.has(cat.id) || (cat.children && cat.children.length > 0)
      )
    }

    filteredCategoryTree.value = buildFilteredTree(categoryTree.value)
  }
  showCategoryDropdown.value = true
}

const selectCategoryItem = (id) => {
  const index = form.categories.indexOf(id)
  if (index > -1) {
    // Already selected, remove it
    form.categories.splice(index, 1)
  } else {
    // Not selected, add it
    form.categories.push(id)
  }
}

const removeCategory = (index) => {
  form.categories.splice(index, 1)
}

const toggleCategory = (id) => {
  // This is handled by CategoryTreeItem component
}

const selectParentCategory = (id) => {
  newCategoryForm.parentId = id
  showParentDropdown.value = false
}

const saveNewCategory = async () => {
  if (!newCategoryForm.title.trim()) {
    showNotification('لطفا نام دسته را وارد کنید', 'error')
    return
  }

  const newCat = {
    typeId: newCategoryForm.typeId?.trim(),
    title: newCategoryForm.title?.trim(),
    slug: newCategoryForm.slug || generateSlugFromText(newCategoryForm.title),
    parentId: newCategoryForm.parentId ?? null,
    description: newCategoryForm.description
  }
  await categoryStore.addCategory(newCat)

  if (newCat.parentId) {
    // Add to parent's children
    const addToParent = (tree) => {
      for (const cat of tree) {
        if (cat.id === newCat.parentId) {
          cat.children.push(newCat)
          return true
        }
        if (cat.children && cat.children.length > 0) {
          if (addToParent(cat.children)) return true
        }
      }
      return false
    }
    addToParent(categoryTree.value)
  } else {
    // Add as root category
    categoryTree.value.push(newCat)
  }

  // Reset form
  newCategoryForm.title = ''
  newCategoryForm.slug = ''
  newCategoryForm.parentId = null
  newCategoryForm.description = ''
  showAddCategoryModal.value = false

  // Update filtered tree
  filteredCategoryTree.value = [...categoryTree.value]

  showNotification(`دسته "${newCat.title}" با موفقیت اضافه شد`, 'success')
}

// Computed properties
const previewContent = computed(() => {
  return form.content // TinyMCE already returns HTML
})

// Content editor handlers
const handleContentChange = (content) => {
  form.content = content
}

const getContentLength = () => {
  // Strip HTML tags to get text length
  const textContent = form.content.replace(/<[^>]*>/g, '')
  return textContent.length
}

// Notification system
const showNotification = (message, type = 'success') => {
  const id = Date.now()
  const notification = {
    id,
    message,
    type,
    progress: 100
  }

  notifications.value.push(notification)

  const timer = setInterval(() => {
    notification.progress -= 2
    if (notification.progress <= 0) {
      clearInterval(timer)
      notifications.value = notifications.value.filter(n => n.id !== id)
    }
  }, 80)
}

// Form validation
const validateForm = () => {
  let isValid = true

  Object.keys(errors).forEach(key => errors[key] = '')

  if (!form.title.trim()) {
    errors.title = 'عنوان الزامی است'
    isValid = false
  }

  if (!form.excerpt.trim()) {
    errors.excerpt = 'خلاصه الزامی است'
    isValid = false
  }

  if (!form.content.trim()) {
    errors.content = 'محتوا الزامی است'
    isValid = false
  }

  if (form.categories.length === 0) {
    errors.category = 'حداقل یک دسته‌بندی الزامی است'
    isValid = false
  }

  return isValid
}
function addTag(tagName) {
  const tag = tagName || newTag.value.trim()
  if (!tag) return

  if (!form.tags.includes(tag)) {
    form.tags.push(tag)

    // اگر تگ از پیشنهادات بود، شمارنده زیاد بشه
    if (tagStore.tags.some(t => t.name === tag)) {
      tagStore.incrementTagCount(tag)
    }
  }
  newTag.value = ''
}
const removeTag = async (index) => {
  const tagName = form.tags[index]
  const tagObj = tagStore.tags.find(t => t.name === tagName)
  if (tagObj) {
    await tagStore.decrementTagCount(tagObj.id)
  }
  form.tags.splice(index, 1)
}

// File handling
const handleFileSelect = (event) => {
  const file = event.target.files[0]
  if (file) {
    handleFile(file)
  }
}

const handleDrop = (event) => {
  event.preventDefault()
  isDragging.value = false

  const files = event.dataTransfer.files
  if (files.length > 0) {
    handleFile(files[0])
  }
}

const handleFile = (file) => {
  if (file.type.startsWith('image/')) {
    if (file.size > 5 * 1024 * 1024) {
      showNotification('حجم فایل نباید بیشتر از 5MB باشد', 'error')
      return
    }

    const reader = new FileReader()
    reader.onload = (e) => {
      form.image = e.target.result
      showNotification('تصویر با موفقیت آپلود شد', 'success')
    }
    reader.readAsDataURL(file)
  } else {
    showNotification('فقط فایل‌های تصویری مجاز هستند', 'error')
  }
}

const removeImage = () => {
  form.image = ''
  showNotification('تصویر حذف شد', 'info')
}

// Actions
const goBack = () => {
  if (hasUnsavedChanges()) {
    if (confirm('تغییرات ذخیره نشده‌ای دارید. آیا مطمئن هستید؟')) {
      window.dispatchEvent(new CustomEvent('navigate-to-posts'))
    }
  } else {
    window.dispatchEvent(new CustomEvent('navigate-to-posts'))
  }
}

const hasUnsavedChanges = () => {
  return form.title || form.excerpt || form.content || form.image || form.tags.length > 0
}

const previewPost = () => {
  showPreviewModal.value = true
}
const postStore = usePostStore()
const saveDraft = async () => {
  if (!form.title.trim()) {
    showNotification('حداقل عنوان را وارد کنید', 'warning')
    return
  }

  isLoading.value = true
  form.status = 'draft'

  try {
    await new Promise(resolve => setTimeout(resolve, 1500))
    showNotification('پیش‌نویس ذخیره شد', 'success')
  } catch (error) {
    showNotification('خطا در ذخیره پیش‌نویس', 'error')
  } finally {
    isLoading.value = false
  }
}

const publishPost = async () => {
  if (!validateForm()) {
    showNotification('لطفا تمام فیلدهای الزامی را پر کنید', 'error')
    return
  }

  isLoading.value = true
  form.status = 'published'

  try {
    await postStore.addPost(form)
    //await new Promise(resolve => setTimeout(resolve, 2000))
    showNotification('نوشته با موفقیت منتشر شد!', 'success')

    setTimeout(() => {
      window.dispatchEvent(new CustomEvent('navigate-to-posts'))
    }, 1500)

  } catch (error) {
    showNotification('خطا در انتشار نوشته', 'error')
  } finally {
    isLoading.value = false
  }
}

// Initialize
onMounted(async () => {
  await categoryTypeStore.fetchType('post')
  await tagTypeStore.fetchType('post')
  // Persian DatePicker handles default date automatically
  // No need for manual initialization
})

watch(
    () => tagTypeStore.selectedType,
    async (type) => {
      if (type?.id) {
        await tagStore.fetchTags({typeId: type.id,contentType:'danim'})
      }
    },
    {immediate: true}
)

watch(
    () => categoryTypeStore.selectedType,
    async (type) => {
      if (type?.id) {
        newCategoryForm.typeId = type.id
        await categoryStore.fetchCategoryTree(type.id)
        await categoryStore.fetchCategories({typeId: type.id,contentType:'danim'})
      }
    },
    {immediate: true}
)

</script>

<style scoped>
.btn-primary {
  background-color: #f97316;
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: background-color 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-primary:hover:not(:disabled) {
  background-color: #ea580c;
}

.btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-secondary {
  background-color: white;
  color: #374151;
  border: 1px solid #d1d5db;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: background-color 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-secondary:hover {
  background-color: #f9fafb;
}

.input-field {
  width: 100%;
  padding: 0.5rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 0.5rem;
  outline: none;
  transition: border-color 0.2s, box-shadow 0.2s;
  background-color: white;
}

.input-field:focus {
  box-shadow: 0 0 0 2px #f97316;
  border-color: transparent;
}

/* Custom Dropdown Animations */
.relative > div[class*="absolute"] {
  animation: slideDown 0.2s ease-out;
}

@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Modal Animation */
.animate-modal {
  animation: modalPop 0.3s ease-out;
}

@keyframes modalPop {
  from {
    opacity: 0;
    transform: scale(0.9);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

/* Scrollbar Styling */
.overflow-y-auto::-webkit-scrollbar {
  width: 6px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 10px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 10px;
}

.overflow-y-auto::-webkit-scrollbar-thumb:hover {
  background: #9ca3af;
}

/* Custom DatePicker Input */
.custom-datepicker-input {
  cursor: pointer;
  background-color: white;
}

.custom-datepicker-input:hover {
  border-color: #f97316;
}

@media (max-width: 1024px) {
  .lg\:col-span-2 {
    grid-column: span 1;
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.animate-spin {
  animation: spin 1s linear infinite;
}

.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

<script>
// Click outside directive for dropdown
export default {
  directives: {
    clickOutside: {
      mounted(el, binding) {
        el.clickOutsideEvent = function (event) {
          if (!(el === event.target || el.contains(event.target))) {
            binding.value()
          }
        }
        document.addEventListener('click', el.clickOutsideEvent)
      },
      unmounted(el) {
        document.removeEventListener('click', el.clickOutsideEvent)
      }
    }
  }
}
</script>